engines:
  radon:
    enabled: true

  duplication:
    enabled: true
    config:
      languages:
      - python
    exclude_fingerprints:
    - b8f2a1e43a0b3b9b0c72906c1ce70b38
    - 51a67d07281197dbafb1a27851a49827
  FIXME:
    enabled: true

ratings:
  paths:
  - pyconfig/

exclude_paths:
- examples/
- tests/
- tools/
- hidden-files/
- "*.md"
- "*.yml"
- "*.ini"
- Makefile
- Dangerfile
- Gemfile
- LICENSE
- pyc.py
- contributing/
- docs/
- setup.py
